---
# run once a week, on push to main, on pr to main
on:
  schedule:
    - @weekly
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          key: "${{ runner.os }}-rust-audit-${{ env.CACHE_VERSION }}-${{ hashFiles('Cargo.lock') }}-${{ github.sha }}"
          restore-keys: |
            ${{ runner.os }}-rust-audit-${{ env.CACHE_VERSION }}-${{ hashFiles('Cargo.lock') }}
            ${{ runner.os }}-rust-audit-${{ env.CACHE_VERSION }}
          path: |
            ~/.cargo/advisory-db/
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: cargo install cargo-audit
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-audit
      - name: cargo audit
        uses: actions-rs/cargo@v1
        with:
          command: audit