---
name: docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

env:
  CACHE_VERSION: v1

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-docker-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-buildx
          path: /tmp/.buildx-cache
      - name: build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false
          tags: naftulikay/fuzzy-datetime:latest
          # we include audit info in the binary, do not strip the binary, and skip the audit and tests because these are
          # handled in other GitHub Actions workflows.
          build-args: |
            RUST_AUDITABLE_BINARY=true
            RUST_STRIP_BINARY=false
            RUST_RUN_AUDIT=false
            RUST_RUN_TESTS=false