---
name: ci

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch: {}

env:
  CACHE_VERSION: v1

jobs:
  benchmarks:
    # FIXME for pull-requests, check out ${{ github.base_ref }}; determine via if: ${{ github.event_name == 'pull_request' }}
    # FIXME for push to main, check out main~1 presumably
    runs-on: ubuntu-latest
    steps:
      # first, we benchmark the reference we're testing against; for pull requests we can use github.base_ref,
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/cache@v3
        with:
          key: "${{ runner.os }}-rust-bench-${{ env.CACHE_VERSION }}-${{ hashFiles('Cargo.lock') }}-${{ github.sha }}"
          restore-keys: |
            ${{ runner.os }}-rust-bench-${{ env.CACHE_VERSION }}-${{ hashFiles('Cargo.lock') }}
            ${{ runner.os }}-rust-bench-${{ env.CACHE_VERSION }}
          path: |
            ~/.cargo
            ./target
      - name: cargo bench (main)
        uses: actions-rs/cargo@v1
        with:
          command: bench
      # benchmark our changes
      - uses: actions/checkout@v3
        with:
          clean: false
      - name: cargo bench (changes)
        uses: actions-rs/cargo@v1
        with:
          command: bench
      # upload report
      - name: upload report
        uses: actions/upload-artifact@v3
        with:
          name: criterion
          path: target/criterion

  build-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/cache@v3
        with:
          key: "${{ runner.os }}-rust-build-debug-${{ env.CACHE_VERSION }}-${{ hashFiles('Cargo.lock') }}-${{ github.sha }}"
          restore-keys: |
            ${{ runner.os }}-rust-build-debug-${{ env.CACHE_VERSION }}-${{ hashFiles('Cargo.lock') }}
            ${{ runner.os }}-rust-build-debug-${{ env.CACHE_VERSION }}
          path: |
            ~/.cargo
            ./target
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features

  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/cache@v3
        with:
          key: "${{ runner.os }}-rust-build-release-${{ env.CACHE_VERSION }}-${{ hashFiles('Cargo.lock') }}-${{ github.sha }}"
          restore-keys: |
            ${{ runner.os }}-rust-build-release-${{ env.CACHE_VERSION }}-${{ hashFiles('Cargo.lock') }}
            ${{ runner.os }}-rust-build-release-${{ env.CACHE_VERSION }}
          path: |
            ~/.cargo
            ./target
      - name: cargo build --release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

  build-static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
      - with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
      - uses: actions/cache@v3
        with:
          key: "${{ runner.os }}-rust-build-static-${{ env.CACHE_VERSION }}-${{ hashFiles('Cargo.lock') }}-${{ github.sha }}"
          restore-keys: |
            ${{ runner.os }}-rust-build-static-${{ env.CACHE_VERSION }}-${{ hashFiles('Cargo.lock') }}
            ${{ runner.os }}-rust-build-static-${{ env.CACHE_VERSION }}
          path: |
            ~/.cargo
            ./target
      - name: cargo build --release (static)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --target x86_64-unknown-linux-musl

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/cache@v3
        with:
          key: "${{ runner.os }}-rust-check-${{ env.CACHE_VERSION }}-${{ hashFiles('Cargo.lock') }}-${{ github.sha }}"
          restore-keys: |
            ${{ runner.os }}-rust-check-${{ env.CACHE_VERSION }}-${{ hashFiles('Cargo.lock') }}
            ${{ runner.os }}-rust-check-${{ env.CACHE_VERSION }}
          path: |
            ~/.cargo
            ./target
      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/cache@v3
        with:
          key: "${{ runner.os }}-rust-lint-${{ env.CACHE_VERSION }}-${{ hashFiles('Cargo.lock') }}-${{ github.sha }}"
          restore-keys: |
            ${{ runner.os }}-rust-lint-${{ env.CACHE_VERSION }}-${{ hashFiles('Cargo.lock') }}
            ${{ runner.os }}-rust-lint-${{ env.CACHE_VERSION }}
          path: |
            ~/.cargo
            ./target
      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/cache@v3
        with:
          key: "${{ runner.os }}-rust-test-${{ env.CACHE_VERSION }}-${{ hashFiles('Cargo.lock') }}-${{ github.sha }}"
          restore-keys: |
            ${{ runner.os }}-rust-test-${{ env.CACHE_VERSION }}-${{ hashFiles('Cargo.lock') }}
            ${{ runner.os }}-rust-test-${{ env.CACHE_VERSION }}
          path: |
            ~/.cargo
            ./target
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose